use_frameworks!

target 'CSSClientB_Example' do
  pod 'CSSClientB', :path => '../'

  target 'CSSClientB_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
