use_frameworks!

target 'CSSClientBProject_Example' do
  pod 'CSSClientBProject', :path => '../'

  target 'CSSClientBProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
